const defaultsourceRelation = {
    id: null,
    leftDatasource: '',
    leftSourceEntity: '',
    leftSourceEntityAlias: '',
    sourceLeftEntityExtractionBundle: '1',
    leftAliasTypeOfDataStore: 'Global_Temp',
    leftSourceAttribute: '',
    leftFilterTransformationRuleLanguage: '',
    leftFilterTransformationRule: 'Passthrough',
    aliasRelationshipTypeLanguage: '',
    aliasRelationshipType: 'inner',
    aliasAttributeRelationshipFilterConditionLanguage: '',
    aliasAttributeRelationshipFilterCondition: 'equal',
    joinMethodLanguage: '',
    joinMethod: 'Column_wise',
    rightDatasource: '',
    rightSourceEntity: '',
    rightSourceEntityAlias: '',
    sourceRightEntityExtractionBundle: '1',
    rightAliasTypeOfDataStore: 'Global_Temp',
    rightSourceAttribute: '',
    rightFilterTransformationRuleLanguage: '',
    rightFilterTransformationRule: 'Passthrough',
    targetTempOutputNumber: '',
    relationshipType: '',
    leftToRightSetInformation: '',
    targetTempTypeOfDataStore: '',
    targetDatasourceName: '',
    targetName: '',
    loadOption: '',
    orderBy: '',
    parallelBundlesExtraction: '',
    parallelBundlesExtractionPriority: '',
    parallelBundlesTransformation: '',
    parallelBundlesLoad: '',
    parallelBundlesLoadPriority: '',
};

export default defaultsourceRelation;